
name: FreeNodeMailer
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - run: pip install -r requirements.txt
      - run: python scripts/fetch.py
      - run: python scripts/send_email.py
        env:
          QQ_EMAIL: ${{ secrets.QQ_EMAIL }}
          QQ_AUTH: ${{ secrets.QQ_AUTH }}
